version: '3'

services:
  php:
    build: 
      context: ./docker/php
    volumes:
      - ./app:/var/www/html

  nginx:
    image: nginx:latest
    ports: 
      - 80:80
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - mysql

  mysql:
    build:
      context: ./docker/volume/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=books_shop_db
      - MYSQL_USER=guest
      - MYSQL_PASSWORD=secret
    volumes:
      - ./docker/volume/dump:/home